
name: Build and Test (Linux)

on: [push]

jobs:
  linux_build:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create Build Directory
        run: cmake -E make_directory ./build/

      - name: Configure CMake
        working-directory: ./build
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Release ../

      - name: Build
        working-directory: ./build
        shell: bash
        run: cmake --build . -j 16
        
      - name: listFiles
        working-directory: ./build
        shell: bash
        run: ls

      - name: Run Tests
        working-directory: ./build
        shell: bash
        run: ctest --verbose
