name: Build and Test (Mac)

on: [push]

jobs:
  mac_build:
    runs-on: [self-hosted, macOS]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Directory
      run: cmake -E make_directory ./build/

    - name: Configure CMake
      working-directory: ./build
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=Release ../

    - name: Build Package
      working-directory: ./build
      shell: bash
      run: cmake --build . -j 2

    - name: Run Tests
      working-directory: ./build
      shell: bash
      run: ctest --verbose
